#!/bin/bash
BUILDKIT="DOCKER_BUILDKIT=1"
DOCKER_BUILD="docker build"
CACHE="--no-cache"
PASSWORD_ROOT="--build-arg POSTGRES_PASSWORD='${POSTGRES_ROOT_PASSWORD}'"
PASSWORD_USER="--build-arg POSTGRES_USER_PASSWORD='${POSTGRES_USER_PASSWORD}'"
REST="-f Dockerfile.psql -t mtw_psql:01 ."
VOLUME=""
CMD="${BUILDKIT} ${DOCKER_BUILD} ${CACHE} ${PASSWORD_ROOT} ${PASSWORD_USER} ${VOLUME} ${REST}"
echo $CMD
eval $CMD

# ROOT_PASSWORD="psql_root_password"
# SECRET_ROOT="--secret id=${ROOT_PASSWORD},env=POSTGRES_PASSWORD"
#USER_PASSWORD="psql_user_password"
#SECRET_USER="--secret id=${USER_PASSWORD},env=POSTGRES_USER_PASSWORD"
# CMD="${BUILDKIT} ${DOCKER_BUILD} ${SECRET_ROOT} ${SECRET_USER} ${REST}"
