version: '3.9'

services:
  svc_postgres:
    image: mtw_psql:01
    user: postgres:postgres
    ports:
        - 5432:5432
    environment:
      - POSTGRES_USER=cb_admin
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=compassblue01
      - POSTGRES_DB_PRODUCTION=cb_production
    volumes:
        - my_vol_05:/var/lib/postgresql/data
    networks:
        - db_network

  svc_django:
    image: mtw:01
    environment:
      - POSTGRES_HOST=svc_postgres
      - REDIS_HOST=svc_redis
    networks:
        - db_network
        - redis_network
    ports:
       - 8000:8000 

  svc_celery:
    image: mtw_celery:01
    environment:
      - POSTGRES_HOST=localhost
      - REDIS_HOST=localhost
    depends_on:
        - svc_redis
    network_mode: host

  svc_redis:
    image: redis:latest
    ports:
        - 6379:6379
    networks:
        - redis_network

volumes:
    my_vol_05:

networks:
  db_network:
  redis_network:
  pub_net:
    driver: macvlan
    driver_opts:
      parent: ens5
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          ip_range: 192.168.1.248/29
          gateway: 192.168.1.1
        

