version: '3.9'

services:
  svc_postgres:
    image: mtw_psql:01
    user: postgres:postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cb_admin
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=compassblue01
      - POSTGRES_DB_PRODUCTION=cb_production
    volumes:
        - my_vol_05:/var/lib/postgresql/data
    networks:
        - db_network

  svc_django:
    image: mtw:01
    ports:
      - 8000:8000
    networks:
        - db_network
        - redis_network

  svc_celery:
    image: mtw_celery:01
    depends_on:
        - svc_redis
    networks:
        - db_network
        - redis_network
    environment:
      - CELERY_BROKER_URL="redis://svc_redis:6379:0"

  svc_redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
        - redis_network

volumes:
    my_vol_05:

networks:
    db_network:
    redis_network:
