version: '3.9'

services:
  svc_postgres:
    image: mtw_psql:01
    user: postgres:postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=cb_admin
      - POSTGRES_PASSWORD=Wt;Sherm9n
      - POSTGRES_DB=compassblue01
      - POSTGRES_DB_PRODUCTION=cb_production
    volumes:
        - my_vol_05:/var/lib/postgresql/data
    networks:
        - db_network

  svc_django:
    image: mtw:01
    ports:
      - 8000:8000
    networks:
        - db_network

volumes:
    my_vol_05:

networks:
    db_network:
