version: '3.9'

services:
  svc_postgres:
    image: mtw_psql:01
    user: postgres:postgres
    ports:
        - 5432:5432
    environment:
      - POSTGRES_USER=cb_admin
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=compassblue01
      - POSTGRES_DB_PRODUCTION=cb_production
    volumes:
        - /home/ubuntu/Pinp01nt/Data/psql:/var/lib/postgresql/data:Z
    networks:
        - db_network

  svc_django:
    image: mtw:01
    environment:
      - POSTGRES_HOST=svc_postgres
      - REDIS_HOST=svc_redis
      - ALLOWED_HOSTS=127.0.0.1,www.pinp01nt.com,54.167.198.200
    volumes:
        - /home/ubuntu/Pinp01nt/Data/app_run:/app/run:Z
    networks:
        - db_network
        - redis_network
    ports:
       - 8000:8000 

  svc_celery:
    image: mtw_celery:01
    environment:
      - POSTGRES_HOST=localhost
      - REDIS_HOST=localhost
      - ZMAP_RUN_DIRECTORY=/app/run/exec_zmap/
      - ZMAP_NUM_THREADS=8
      - ZMAP_PING_RATE=10000
    volumes:
        - /home/ubuntu/Pinp01nt/Data/app_run:/app/run:Z
    depends_on:
        - svc_redis
    network_mode: host

  svc_cbeat:
    image: mtw_cbeat:01
    environment:
      - REDIS_HOST=svc_redis
      - POSTGRES_HOST=svc_postgres
    volumes:
        - /home/ubuntu/Pinp01nt/Data/app_run:/app/run:Z
    networks:
        - db_network
        - redis_network
    depends_on:
        - svc_redis

  svc_redis:
    image: redis:latest
    ports:
        - 6379:6379
    networks:
        - redis_network

volumes:
    my_vol_05:

networks:
  db_network:
  redis_network:
#        - my_vol_05:/var/lib/postgresql/data
